
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Squares(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);

squares mysquares(
		CLOCK_50,       //   clk.clk
		{HEX5, HEX4, HEX3, HEX2, HEX1, HEX0},
		KEY,
		LEDR,
		PS2_CLK,        //   ps2.ps2_clk
		PS2_DAT,        //      .ps2_data
		1'b1,           // nreset
		SW,
		VGA_CLK,       //   vga.CLK
		VGA_HS,        //      .HS
		VGA_VS,        //      .VS
		VGA_BLANK_N,     //      .BLANK
		VGA_SYNC_N,      //      .SYNC
		VGA_R,         //      .R
		VGA_G,         //      .G
		VGA_B          //      .B
	);


endmodule
